apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-agent
  namespace: azure-devops-agents
spec:
  replicas: 1  # Number of agents you want to run
  selector:
    matchLabels:
      app: azure-devops-agent
  template:
    metadata:
      labels:
        app: azure-devops-agent
    spec:
      containers:
      - name: azure-devops-agent
        image: shalevnatan6/azure:1
        env:
        - name: AZP_URL
          value: "<YOUR_REPO_URL"  # Replace with your Azure DevOps org
        - name: AZP_TOKEN
          value: "<YOUR_TOKEN>"  # Replace with a Personal Access Token
        - name: AZP_POOL
          value: "<YOUR_POOL>"  # Pool name in Azure DevOps
        - name: AZP_AGENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock  # Required for building Docker images
        lifecycle:
          preStop:
            exec:
              command: ["./config.sh", "remove", "--auth", "PAT", "--token", "${AZP_TOKEN}"]
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
