apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-agent
  namespace: ns-azure-agents
spec:
  replicas: 10
  selector:
    matchLabels:
      app: azure-devops-agent
  template:
    metadata:
      labels:
        app: azure-devops-agent
    spec:
      serviceAccountName: azure-devops-agent-sa
      containers:
      - name: azure-devops-agent
        image: shalevnatan6/azure:1
        env:
        - name: AZP_URL
          valueFrom:
            configMapKeyRef:
              name: azure-devops-agent-config
              key: AZURE_DEVOPS_URL
        - name: AZP_POOL
          valueFrom:
            configMapKeyRef:
              name: azure-devops-agent-config
              key: AZURE_DEVOPS_POOL
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: azure-devops-agent-secret
              key: PAT
        - name: AZP_AGENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        lifecycle:
          preStop:
            exec:
              command: ["bash", "-c", "./config.sh remove --auth PAT --token $AZP_TOKEN"]
      volumes:
      - name: workspace
        emptyDir: {}
